AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda test

Globals:
  Api:
    Name: !Sub api-${AWS::StackName}
    TracingEnabled: true
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'*'"
      AllowHeaders: "'*'"

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      MemorySize: 128
      Timeout: 360
      FunctionName: !Sub users-${AWS::StackName}
      Description: !Sub users
      CodeUri: modules/users
      Handler: app.lambda_handler
      Environment:
        Variables:
          POSTGRES_HOST: "database-1.clqf4hnirkkf.us-east-1.rds.amazonaws.com"
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_PORT: 5432
      Events:
        getUser:
          Type: Api
          Properties:
            Path: /users
            Method: get
        createUser:
          Type: Api
          Properties:
            Path: /users
            Method: post