AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda test

Parameters:
  DataBaseDB:
    Description: Database DB
    Type: AWS::SSM::Parameter::Value<String>
    Default: DataBaseDB
  DataBaseHost:
    Description: Host Database
    Type: AWS::SSM::Parameter::Value<String>
    Default: DataBaseHost
  DataBasePassword:
    Description: Password Database
    Type: AWS::SSM::Parameter::Value<String>
    Default: DataBasePassword
  DataBasePort:
    Description: Port Database
    Type: AWS::SSM::Parameter::Value<String>
    Default: DataBasePort
  DataBaseUser:
    Description: User Database
    Type: AWS::SSM::Parameter::Value<String>
    Default: DataBaseUser
  AwsAccessKeyId:
    Description: Aws Access Key Id
    Type: AWS::SSM::Parameter::Value<String>
    Default: AwsAccessKeyId
  AwsSecretAccessKey:
    Description: Aws secret access key
    Type: AWS::SSM::Parameter::Value<String>
    Default: AwsSecretAccessKey
  SecretKey:
    Description: Secret Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: SecretKey
  AwsRegion:
    Description: Aws Region
    Type: AWS::SSM::Parameter::Value<String>
    Default: AwsRegion
  
Globals:
  Api:
    Name: !Sub api-${AWS::StackName}
    TracingEnabled: true
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'*'"
      AllowHeaders: "'*'"

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      MemorySize: 128
      Timeout: 360
      FunctionName: !Sub users-${AWS::StackName}
      Description: !Sub users
      CodeUri: modules/users
      Handler: app.lambda_handler
      Environment:
        Variables:
          POSTGRES_HOST: !Ref DataBaseHost
          POSTGRES_USER: !Ref DataBaseUser
          POSTGRES_DB: !Ref DataBaseDB
          POSTGRES_PASSWORD: !Ref DataBasePassword
          POSTGRES_PORT: !Ref DataBasePort
          AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
          AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
          SECRET_KEY: !Ref SecretKey
          DYNAMODB_TABLE: !Sub authorizer-table
          AWS_REGION: !Ref AwsRegion
      Events:
        getUser:
          Type: Api
          Properties:
            Path: /users
            Method: get
        createUser:
          Type: Api
          Properties:
            Path: /users
            Method: post
        UserById:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: any
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
  AuthorizerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub authorizer-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5